# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_ui/home_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1198, 829)
        MainWindow.setStyleSheet("/* stle for tool buttons */\n"
"\n"
"QToolButton {\n"
"background-color:transparent;\n"
"border:1px solid blue;\n"
"border-radius:10px;\n"
"padding:5px;\n"
"}\n"
"\n"
"QToolButton:hover{\n"
"background-color: grey;\n"
"\n"
"}\n"
"QLineEdit{\n"
"padding-left:10px;\n"
"font-size:20px;\n"
"color:blue;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.main_tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.main_tabWidget.setFont(font)
        self.main_tabWidget.setMouseTracking(False)
        self.main_tabWidget.setTabBarAutoHide(True)
        self.main_tabWidget.setObjectName("main_tabWidget")
        self.today_tabWidget = QtWidgets.QWidget()
        self.today_tabWidget.setObjectName("today_tabWidget")
        self.today_tableWidget = QtWidgets.QTableWidget(self.today_tabWidget)
        self.today_tableWidget.setGeometry(QtCore.QRect(0, 120, 971, 531))
        self.today_tableWidget.setObjectName("today_tableWidget")
        self.today_tableWidget.setColumnCount(9)
        self.today_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.today_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.today_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.today_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.today_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.today_tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.today_tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.today_tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.today_tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.today_tableWidget.setHorizontalHeaderItem(8, item)
        self.name_customer_line_edit = QtWidgets.QLineEdit(self.today_tabWidget)
        self.name_customer_line_edit.setGeometry(QtCore.QRect(20, 20, 241, 31))
        self.name_customer_line_edit.setObjectName("name_customer_line_edit")
        self.name_book_line_edit = QtWidgets.QLineEdit(self.today_tabWidget)
        self.name_book_line_edit.setGeometry(QtCore.QRect(20, 60, 241, 31))
        self.name_book_line_edit.setObjectName("name_book_line_edit")
        self.type_combobox = QtWidgets.QComboBox(self.today_tabWidget)
        self.type_combobox.setGeometry(QtCore.QRect(270, 20, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.type_combobox.setFont(font)
        self.type_combobox.setObjectName("type_combobox")
        self.type_combobox.addItem("")
        self.type_combobox.addItem("")
        self.days_combobox = QtWidgets.QComboBox(self.today_tabWidget)
        self.days_combobox.setGeometry(QtCore.QRect(270, 60, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.days_combobox.setFont(font)
        self.days_combobox.setObjectName("days_combobox")
        self.days_combobox.addItem("")
        self.days_combobox.addItem("")
        self.days_combobox.addItem("")
        self.days_combobox.addItem("")
        self.days_combobox.addItem("")
        self.days_combobox.addItem("")
        self.days_combobox.addItem("")
        self.days_combobox.addItem("")
        self.days_combobox.addItem("")
        self.days_combobox.addItem("")
        self.days_combobox.addItem("")
        self.days_combobox.addItem("")
        self.days_combobox.addItem("")
        self.days_combobox.addItem("")
        self.days_combobox.addItem("")
        self.days_combobox.addItem("")
        self.days_combobox.addItem("")
        self.days_combobox.addItem("")
        self.days_combobox.addItem("")
        self.days_combobox.addItem("")
        self.days_combobox.addItem("")
        self.days_combobox.addItem("")
        self.days_combobox.addItem("")
        self.days_combobox.addItem("")
        self.days_combobox.addItem("")
        self.days_combobox.addItem("")
        self.days_combobox.addItem("")
        self.days_combobox.addItem("")
        self.days_combobox.addItem("")
        self.days_combobox.addItem("")
        self.add_operation_btn = QtWidgets.QPushButton(self.today_tabWidget)
        self.add_operation_btn.setGeometry(QtCore.QRect(530, 30, 121, 51))
        self.add_operation_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_operation_btn.setStyleSheet("#add_operation_btn {\n"
"font-size:22px;\n"
"background-color:blue;\n"
"border-radius:25px;\n"
"color:white;\n"
"}\n"
"\n"
"#add_operation_btn:hover{\n"
"background-color:#fff;\n"
"border:1px solid red;\n"
"color:black;\n"
"}")
        self.add_operation_btn.setObjectName("add_operation_btn")
        self.main_tabWidget.addTab(self.today_tabWidget, "")
        self.QWidget = QtWidgets.QWidget()
        self.QWidget.setObjectName("QWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.QWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.books_tabWidget = QtWidgets.QTabWidget(self.QWidget)
        self.books_tabWidget.setObjectName("books_tabWidget")
        self.Edit_book_tabWidget = QtWidgets.QWidget()
        self.Edit_book_tabWidget.setObjectName("Edit_book_tabWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Edit_book_tabWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.Edit_book_tabWidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(20, 10, 539, 571))
        self.frame_3.setStyleSheet("width: 606px;\n"
"height: 662px;\n"
"flex-shrink: 0;\n"
"border-radius: 22px;\n"
"background: #F3F3F3;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setStyleSheet("display: flex;\n"
"width: 147px;\n"
"height: 20px;\n"
"flex-direction: column;\n"
"justify-content: center;\n"
"flex-shrink: 0;\n"
"color: #000;\n"
"font-family: \"Rounded Mplus 1c\";\n"
"font-size: 20px;\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"line-height: normal;")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.book_title_lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.book_title_lineEdit.setStyleSheet("width: 509px;\n"
"height: 45px;\n"
"flex-shrink: 0;\n"
"border-radius: 7px;\n"
"background: #E4E4E4;")
        self.book_title_lineEdit.setObjectName("book_title_lineEdit")
        self.verticalLayout_2.addWidget(self.book_title_lineEdit)
        self.gridLayout_4.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setStyleSheet("display: flex;\n"
"width: 147px;\n"
"height: 20px;\n"
"flex-direction: column;\n"
"justify-content: center;\n"
"flex-shrink: 0;\n"
"color: #000;\n"
"font-family: \"Rounded Mplus 1c\";\n"
"font-size: 20px;\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"line-height: normal;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.book_id_lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.book_id_lineEdit.setStyleSheet("width: 509px;\n"
"height: 45px;\n"
"flex-shrink: 0;\n"
"border-radius: 7px;\n"
"background: #E4E4E4;")
        self.book_id_lineEdit.setObjectName("book_id_lineEdit")
        self.verticalLayout_3.addWidget(self.book_id_lineEdit)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setStyleSheet("display: flex;\n"
"width: 147px;\n"
"height: 20px;\n"
"flex-direction: column;\n"
"justify-content: center;\n"
"flex-shrink: 0;\n"
"color: #000;\n"
"font-family: \"Rounded Mplus 1c\";\n"
"font-size: 20px;\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"line-height: normal;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.book_auther_lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.book_auther_lineEdit.setStyleSheet("width: 509px;\n"
"height: 45px;\n"
"flex-shrink: 0;\n"
"border-radius: 7px;\n"
"background: #E4E4E4;")
        self.book_auther_lineEdit.setObjectName("book_auther_lineEdit")
        self.verticalLayout_4.addWidget(self.book_auther_lineEdit)
        self.gridLayout_4.addLayout(self.verticalLayout_4, 2, 0, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setStyleSheet("display: flex;\n"
"width: 147px;\n"
"height: 20px;\n"
"flex-direction: column;\n"
"justify-content: center;\n"
"flex-shrink: 0;\n"
"color: #000;\n"
"font-family: \"Rounded Mplus 1c\";\n"
"font-size: 20px;\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"line-height: normal;")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.book_price_lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.book_price_lineEdit.setStyleSheet("width: 509px;\n"
"height: 45px;\n"
"flex-shrink: 0;\n"
"border-radius: 7px;\n"
"background: #E4E4E4;")
        self.book_price_lineEdit.setObjectName("book_price_lineEdit")
        self.verticalLayout_6.addWidget(self.book_price_lineEdit)
        self.gridLayout_4.addLayout(self.verticalLayout_6, 4, 0, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(12)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setStyleSheet("display: flex;\n"
"width: 147px;\n"
"height: 20px;\n"
"flex-direction: column;\n"
"justify-content: center;\n"
"flex-shrink: 0;\n"
"color: #000;\n"
"font-family: \"Rounded Mplus 1c\";\n"
"font-size: 20px;\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"line-height: normal;")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.book_category_lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.book_category_lineEdit.setStyleSheet("width: 509px;\n"
"height: 45px;\n"
"flex-shrink: 0;\n"
"border-radius: 7px;\n"
"background: #E4E4E4;")
        self.book_category_lineEdit.setObjectName("book_category_lineEdit")
        self.verticalLayout_7.addWidget(self.book_category_lineEdit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(60)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.upload_btn = QtWidgets.QPushButton(self.frame_3)
        self.upload_btn.setMaximumSize(QtCore.QSize(300, 40))
        self.upload_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.upload_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.upload_btn.setAutoFillBackground(False)
        self.upload_btn.setStyleSheet("#upload_btn {\n"
"background-color: sky;\n"
"border-radius:20px;\n"
"color:white;\n"
"font-size:20px;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("qt_ui\\../assets/image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.upload_btn.setIcon(icon)
        self.upload_btn.setIconSize(QtCore.QSize(24, 24))
        self.upload_btn.setObjectName("upload_btn")
        self.horizontalLayout_2.addWidget(self.upload_btn)
        self.upload_image_label = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.upload_image_label.setFont(font)
        self.upload_image_label.setObjectName("upload_image_label")
        self.horizontalLayout_2.addWidget(self.upload_image_label)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.gridLayout_4.addLayout(self.verticalLayout_7, 5, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setStyleSheet("display: flex;\n"
"width: 147px;\n"
"height: 20px;\n"
"flex-direction: column;\n"
"justify-content: center;\n"
"flex-shrink: 0;\n"
"color: #000;\n"
"font-family: \"Rounded Mplus 1c\";\n"
"font-size: 20px;\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"line-height: normal;")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.book_publisher_lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.book_publisher_lineEdit.setStyleSheet("width: 509px;\n"
"height: 45px;\n"
"flex-shrink: 0;\n"
"border-radius: 7px;\n"
"background: #E4E4E4;")
        self.book_publisher_lineEdit.setObjectName("book_publisher_lineEdit")
        self.verticalLayout_5.addWidget(self.book_publisher_lineEdit)
        self.gridLayout_4.addLayout(self.verticalLayout_5, 3, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(590, 10, 401, 271))
        self.frame_4.setStyleSheet("flex-shrink: 0;\n"
"border-radius: 22px;\n"
"background: #F3F3F3;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.layoutWidget_2 = QtWidgets.QWidget(self.frame_4)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 30, 371, 231))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_10.setContentsMargins(5, 2, 5, 2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_8.setStyleSheet("display: flex;\n"
"width: 147px;\n"
"height: 20px;\n"
"flex-direction: column;\n"
"justify-content: center;\n"
"flex-shrink: 0;\n"
"color: #000;\n"
"font-family: \"Rounded Mplus 1c\";\n"
"font-size: 20px;\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"line-height: normal;")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_10.addWidget(self.label_8)
        self.desc_textEdit = QtWidgets.QTextEdit(self.layoutWidget_2)
        self.desc_textEdit.setStyleSheet("border-radius: 7px;\n"
"background: #E4E4E4;\n"
"padding:10px;\n"
"font-size:20px;\n"
"color:blue;")
        self.desc_textEdit.setObjectName("desc_textEdit")
        self.verticalLayout_10.addWidget(self.desc_textEdit)
        self.layoutWidget_3 = QtWidgets.QWidget(self.frame_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(590, 290, 441, 311))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_11.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout_11.setContentsMargins(40, 10, 40, 10)
        self.verticalLayout_11.setSpacing(5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.save_btn = QtWidgets.QPushButton(self.layoutWidget_3)
        self.save_btn.setMinimumSize(QtCore.QSize(100, 50))
        self.save_btn.setMaximumSize(QtCore.QSize(45665, 16777215))
        self.save_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.save_btn.setStyleSheet("#save_btn{\n"
"font-size:22px;\n"
"background-color:#1678F3;;\n"
"color:white;\n"
"border-radius:25px;\n"
"border:1px solid blue;\n"
"}\n"
"#save_btn:hover{\n"
"background-color:blue;;\n"
"color:white;\n"
"}")
        self.save_btn.setObjectName("save_btn")
        self.verticalLayout_11.addWidget(self.save_btn)
        self.search_btn = QtWidgets.QPushButton(self.layoutWidget_3)
        self.search_btn.setMinimumSize(QtCore.QSize(0, 50))
        self.search_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.search_btn.setStyleSheet("#search_btn{\n"
"font-size:22px;\n"
"background-color:#B5FFE1;;\n"
"color:black;\n"
"border-radius:25px;\n"
"border:1px solid blue;\n"
"}\n"
"#search_btn:hover{\n"
"background-color:#388697;;\n"
"color:white;\n"
"}")
        self.search_btn.setObjectName("search_btn")
        self.verticalLayout_11.addWidget(self.search_btn)
        self.update_btn = QtWidgets.QPushButton(self.layoutWidget_3)
        self.update_btn.setMinimumSize(QtCore.QSize(0, 50))
        self.update_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.update_btn.setStyleSheet("#update_btn{\n"
"font-size:22px;\n"
"background-color:#08415C;;\n"
"color:white;\n"
"border-radius:25px;\n"
"border:1px solid blue;\n"
"}\n"
"#update_btn:hover{\n"
"background-color:#388697;\n"
"color:white;\n"
"}\n"
"#update_btn:disabled {\n"
"background-color: #A9A9A9;  /* Grey background when disabled */\n"
"color: #808080;  /* Grey text when disabled */\n"
"}")
        self.update_btn.setObjectName("update_btn")
        self.verticalLayout_11.addWidget(self.update_btn)
        self.delete_btn = QtWidgets.QPushButton(self.layoutWidget_3)
        self.delete_btn.setMinimumSize(QtCore.QSize(0, 50))
        self.delete_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_btn.setStyleSheet("#delete_btn{\n"
"font-size:22px;\n"
"background-color:red;;\n"
"color:white;\n"
"border-radius:25px;\n"
"border:1px solid blue;\n"
"}\n"
"#delete_btn:hover{\n"
"background-color:#CC2936;;\n"
"color:white;\n"
"}\n"
"#delete_btn:disabled {\n"
"background-color: #A9A9A9;  /* Grey background when disabled */\n"
"color: #808080;  /* Grey text when disabled */\n"
"}")
        self.delete_btn.setObjectName("delete_btn")
        self.verticalLayout_11.addWidget(self.delete_btn)
        self.clear_btn = QtWidgets.QPushButton(self.layoutWidget_3)
        self.clear_btn.setMinimumSize(QtCore.QSize(0, 50))
        self.clear_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.clear_btn.setStyleSheet("#clear_btn{\n"
"font-size:22px;\n"
"background-color:green;;\n"
"color:white;\n"
"border-radius:25px;\n"
"border:1px solid blue;\n"
"}\n"
"#clear_btn:hover{\n"
"background-color:#CC2936;;\n"
"color:white;\n"
"}")
        self.clear_btn.setObjectName("clear_btn")
        self.verticalLayout_11.addWidget(self.clear_btn)
        self.horizontalLayout.addWidget(self.frame_2)
        self.books_tabWidget.addTab(self.Edit_book_tabWidget, "")
        self.show_books_tabWidget = QtWidgets.QWidget()
        self.show_books_tabWidget.setObjectName("show_books_tabWidget")
        self.show_books_tableWidget = QtWidgets.QTableWidget(self.show_books_tabWidget)
        self.show_books_tableWidget.setGeometry(QtCore.QRect(0, 0, 1021, 651))
        self.show_books_tableWidget.setObjectName("show_books_tableWidget")
        self.show_books_tableWidget.setColumnCount(6)
        self.show_books_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.show_books_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.show_books_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.show_books_tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.show_books_tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.show_books_tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.show_books_tableWidget.setHorizontalHeaderItem(5, item)
        self.books_tabWidget.addTab(self.show_books_tabWidget, "")
        self.gridLayout_2.addWidget(self.books_tabWidget, 0, 0, 1, 1)
        self.main_tabWidget.addTab(self.QWidget, "")
        self.users_tabWidget = QtWidgets.QWidget()
        self.users_tabWidget.setObjectName("users_tabWidget")
        self.frame_5 = QtWidgets.QFrame(self.users_tabWidget)
        self.frame_5.setGeometry(QtCore.QRect(20, 20, 1011, 611))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setGeometry(QtCore.QRect(0, 0, 551, 611))
        self.frame_6.setStyleSheet("width: 606px;\n"
"height: 662px;\n"
"flex-shrink: 0;\n"
"border-radius: 22px;\n"
"background: #F3F3F3;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.layoutWidget_4 = QtWidgets.QWidget(self.frame_6)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 25, 541, 445))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_9.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_9.setSpacing(10)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_7.setStyleSheet("display: flex;\n"
"width: 147px;\n"
"height: 20px;\n"
"flex-direction: column;\n"
"justify-content: center;\n"
"flex-shrink: 0;\n"
"color: #000;\n"
"font-family: \"Rounded Mplus 1c\";\n"
"font-size: 20px;\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"line-height: normal;")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_12.addWidget(self.label_7)
        self.username_lineEdit = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.username_lineEdit.setStyleSheet("width: 509px;\n"
"height: 45px;\n"
"flex-shrink: 0;\n"
"border-radius: 7px;\n"
"background: #E4E4E4;")
        self.username_lineEdit.setObjectName("username_lineEdit")
        self.verticalLayout_12.addWidget(self.username_lineEdit)
        self.verticalLayout_9.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_9.setStyleSheet("display: flex;\n"
"width: 147px;\n"
"height: 20px;\n"
"flex-direction: column;\n"
"justify-content: center;\n"
"flex-shrink: 0;\n"
"color: #000;\n"
"font-family: \"Rounded Mplus 1c\";\n"
"font-size: 20px;\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"line-height: normal;")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_13.addWidget(self.label_9)
        self.name_lineEdit = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.name_lineEdit.setStyleSheet("width: 509px;\n"
"height: 45px;\n"
"flex-shrink: 0;\n"
"border-radius: 7px;\n"
"background: #E4E4E4;")
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.verticalLayout_13.addWidget(self.name_lineEdit)
        self.verticalLayout_9.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_10.setStyleSheet("display: flex;\n"
"width: 147px;\n"
"height: 20px;\n"
"flex-direction: column;\n"
"justify-content: center;\n"
"flex-shrink: 0;\n"
"color: #000;\n"
"font-family: \"Rounded Mplus 1c\";\n"
"font-size: 20px;\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"line-height: normal;")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_14.addWidget(self.label_10)
        self.email_lineEdit = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.email_lineEdit.setStyleSheet("width: 509px;\n"
"height: 45px;\n"
"flex-shrink: 0;\n"
"border-radius: 7px;\n"
"background: #E4E4E4;")
        self.email_lineEdit.setObjectName("email_lineEdit")
        self.verticalLayout_14.addWidget(self.email_lineEdit)
        self.verticalLayout_9.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_11.setStyleSheet("display: flex;\n"
"width: 147px;\n"
"height: 20px;\n"
"flex-direction: column;\n"
"justify-content: center;\n"
"flex-shrink: 0;\n"
"color: #000;\n"
"font-family: \"Rounded Mplus 1c\";\n"
"font-size: 20px;\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"line-height: normal;")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_15.addWidget(self.label_11)
        self.password_lineEdit = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.password_lineEdit.setStyleSheet("width: 509px;\n"
"height: 45px;\n"
"flex-shrink: 0;\n"
"border-radius: 7px;\n"
"background: #E4E4E4;")
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.verticalLayout_15.addWidget(self.password_lineEdit)
        self.verticalLayout_9.addLayout(self.verticalLayout_15)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_12.setStyleSheet("display: flex;\n"
"width: 147px;\n"
"height: 20px;\n"
"flex-direction: column;\n"
"justify-content: center;\n"
"flex-shrink: 0;\n"
"color: #000;\n"
"font-family: \"Rounded Mplus 1c\";\n"
"font-size: 20px;\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"line-height: normal;")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_16.addWidget(self.label_12)
        self.conferm_password_lineEdit = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.conferm_password_lineEdit.setStyleSheet("width: 509px;\n"
"height: 45px;\n"
"flex-shrink: 0;\n"
"border-radius: 7px;\n"
"background: #E4E4E4;")
        self.conferm_password_lineEdit.setObjectName("conferm_password_lineEdit")
        self.verticalLayout_16.addWidget(self.conferm_password_lineEdit)
        self.verticalLayout_9.addLayout(self.verticalLayout_16)
        self.user_radioButton = QtWidgets.QRadioButton(self.frame_6)
        self.user_radioButton.setEnabled(True)
        self.user_radioButton.setGeometry(QtCore.QRect(150, 530, 82, 17))
        self.user_radioButton.setChecked(True)
        self.user_radioButton.setObjectName("user_radioButton")
        self.admin_radioButton = QtWidgets.QRadioButton(self.frame_6)
        self.admin_radioButton.setGeometry(QtCore.QRect(280, 530, 82, 17))
        self.admin_radioButton.setObjectName("admin_radioButton")
        self.layoutWidget_6 = QtWidgets.QWidget(self.frame_5)
        self.layoutWidget_6.setGeometry(QtCore.QRect(560, 0, 411, 321))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_19.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout_19.setContentsMargins(40, 10, 40, 10)
        self.verticalLayout_19.setSpacing(10)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.save_btn_2 = QtWidgets.QPushButton(self.layoutWidget_6)
        self.save_btn_2.setMinimumSize(QtCore.QSize(0, 60))
        self.save_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.save_btn_2.setStyleSheet("#save_btn_2{\n"
"font-size:22px;\n"
"background-color:#1678F3;;\n"
"color:white;\n"
"border-radius:30px;\n"
"border:1px solid blue;\n"
"}\n"
"#save_btn_2:hover{\n"
"background-color:blue;;\n"
"color:white;\n"
"}")
        self.save_btn_2.setObjectName("save_btn_2")
        self.verticalLayout_19.addWidget(self.save_btn_2)
        self.search_btn_2 = QtWidgets.QPushButton(self.layoutWidget_6)
        self.search_btn_2.setMinimumSize(QtCore.QSize(0, 60))
        self.search_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.search_btn_2.setStyleSheet("#search_btn_2{\n"
"font-size:22px;\n"
"background-color:#B5FFE1;;\n"
"color:black;\n"
"border-radius:30px;\n"
"border:1px solid blue;\n"
"}\n"
"#search_btn_2:hover{\n"
"background-color:#388697;;\n"
"color:white;\n"
"}")
        self.search_btn_2.setObjectName("search_btn_2")
        self.verticalLayout_19.addWidget(self.search_btn_2)
        self.update_btn_2 = QtWidgets.QPushButton(self.layoutWidget_6)
        self.update_btn_2.setMinimumSize(QtCore.QSize(0, 60))
        self.update_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.update_btn_2.setStyleSheet("#update_btn_2{\n"
"font-size:22px;\n"
"background-color:#08415C;;\n"
"color:white;\n"
"border-radius:30px;\n"
"border:1px solid blue;\n"
"}\n"
"#update_btn_2:hover{\n"
"background-color:#388697;\n"
"color:white;\n"
"}\n"
"#update_btn_2:disabled {\n"
"background-color: #A9A9A9;  /* Grey background when disabled */\n"
"color: #808080;  /* Grey text when disabled */\n"
"}")
        self.update_btn_2.setObjectName("update_btn_2")
        self.verticalLayout_19.addWidget(self.update_btn_2)
        self.delete_btn_2 = QtWidgets.QPushButton(self.layoutWidget_6)
        self.delete_btn_2.setMinimumSize(QtCore.QSize(0, 60))
        self.delete_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_btn_2.setStyleSheet("#delete_btn_2{\n"
"font-size:22px;\n"
"background-color:red;;\n"
"color:white;\n"
"border-radius:30px;\n"
"border:1px solid blue;\n"
"}\n"
"#delete_btn_2:hover{\n"
"background-color:#CC2936;;\n"
"color:white;\n"
"}\n"
"#delete_btn_2:disabled {\n"
"background-color: #A9A9A9;  /* Grey background when disabled */\n"
"color: #808080;  /* Grey text when disabled */\n"
"}")
        self.delete_btn_2.setObjectName("delete_btn_2")
        self.verticalLayout_19.addWidget(self.delete_btn_2)
        self.users_tableWidget = QtWidgets.QTableWidget(self.frame_5)
        self.users_tableWidget.setGeometry(QtCore.QRect(560, 330, 441, 271))
        self.users_tableWidget.setObjectName("users_tableWidget")
        self.users_tableWidget.setColumnCount(3)
        self.users_tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.users_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.users_tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.users_tableWidget.setHorizontalHeaderItem(2, item)
        self.main_tabWidget.addTab(self.users_tabWidget, "")
        self.settings_tabWidget = QtWidgets.QWidget()
        self.settings_tabWidget.setObjectName("settings_tabWidget")
        self.main_tabWidget.addTab(self.settings_tabWidget, "")
        self.gridLayout.addWidget(self.main_tabWidget, 0, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.today_tool_btn = QtWidgets.QToolButton(self.frame)
        self.today_tool_btn.setStyleSheet("")
        self.today_tool_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("qt_ui\\../assets/today.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.today_tool_btn.setIcon(icon1)
        self.today_tool_btn.setIconSize(QtCore.QSize(60, 60))
        self.today_tool_btn.setObjectName("today_tool_btn")
        self.verticalLayout.addWidget(self.today_tool_btn)
        self.books_tool_btn = QtWidgets.QToolButton(self.frame)
        self.books_tool_btn.setStyleSheet("")
        self.books_tool_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("qt_ui\\../assets/book.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.books_tool_btn.setIcon(icon2)
        self.books_tool_btn.setIconSize(QtCore.QSize(60, 60))
        self.books_tool_btn.setObjectName("books_tool_btn")
        self.verticalLayout.addWidget(self.books_tool_btn)
        self.users_tool_btn = QtWidgets.QToolButton(self.frame)
        self.users_tool_btn.setStyleSheet("")
        self.users_tool_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("qt_ui\\../assets/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.users_tool_btn.setIcon(icon3)
        self.users_tool_btn.setIconSize(QtCore.QSize(60, 60))
        self.users_tool_btn.setObjectName("users_tool_btn")
        self.verticalLayout.addWidget(self.users_tool_btn)
        self.settings_tool_btn = QtWidgets.QToolButton(self.frame)
        self.settings_tool_btn.setStyleSheet("")
        self.settings_tool_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("qt_ui\\../assets/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settings_tool_btn.setIcon(icon4)
        self.settings_tool_btn.setIconSize(QtCore.QSize(60, 60))
        self.settings_tool_btn.setObjectName("settings_tool_btn")
        self.verticalLayout.addWidget(self.settings_tool_btn)
        self.themes_tool_btn = QtWidgets.QToolButton(self.frame)
        self.themes_tool_btn.setStyleSheet("")
        self.themes_tool_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("qt_ui\\../assets/app-design.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.themes_tool_btn.setIcon(icon5)
        self.themes_tool_btn.setIconSize(QtCore.QSize(60, 60))
        self.themes_tool_btn.setObjectName("themes_tool_btn")
        self.verticalLayout.addWidget(self.themes_tool_btn)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1198, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.main_tabWidget.setCurrentIndex(0)
        self.books_tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.today_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "user name"))
        item = self.today_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Book Id"))
        item = self.today_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Book Title"))
        item = self.today_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Book Auther"))
        item = self.today_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Book Publisher"))
        item = self.today_tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Book Category"))
        item = self.today_tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Book Price"))
        item = self.today_tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "type"))
        item = self.today_tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "days"))
        self.name_customer_line_edit.setPlaceholderText(_translate("MainWindow", "name of customer"))
        self.name_book_line_edit.setPlaceholderText(_translate("MainWindow", "name of the book"))
        self.type_combobox.setItemText(0, _translate("MainWindow", "Sell"))
        self.type_combobox.setItemText(1, _translate("MainWindow", "Rent"))
        self.days_combobox.setItemText(0, _translate("MainWindow", "1"))
        self.days_combobox.setItemText(1, _translate("MainWindow", "2"))
        self.days_combobox.setItemText(2, _translate("MainWindow", "3"))
        self.days_combobox.setItemText(3, _translate("MainWindow", "4"))
        self.days_combobox.setItemText(4, _translate("MainWindow", "5"))
        self.days_combobox.setItemText(5, _translate("MainWindow", "6"))
        self.days_combobox.setItemText(6, _translate("MainWindow", "7"))
        self.days_combobox.setItemText(7, _translate("MainWindow", "8"))
        self.days_combobox.setItemText(8, _translate("MainWindow", "9"))
        self.days_combobox.setItemText(9, _translate("MainWindow", "10"))
        self.days_combobox.setItemText(10, _translate("MainWindow", "11"))
        self.days_combobox.setItemText(11, _translate("MainWindow", "12"))
        self.days_combobox.setItemText(12, _translate("MainWindow", "13"))
        self.days_combobox.setItemText(13, _translate("MainWindow", "14"))
        self.days_combobox.setItemText(14, _translate("MainWindow", "15"))
        self.days_combobox.setItemText(15, _translate("MainWindow", "16"))
        self.days_combobox.setItemText(16, _translate("MainWindow", "17"))
        self.days_combobox.setItemText(17, _translate("MainWindow", "18"))
        self.days_combobox.setItemText(18, _translate("MainWindow", "19"))
        self.days_combobox.setItemText(19, _translate("MainWindow", "20"))
        self.days_combobox.setItemText(20, _translate("MainWindow", "21"))
        self.days_combobox.setItemText(21, _translate("MainWindow", "22"))
        self.days_combobox.setItemText(22, _translate("MainWindow", "23"))
        self.days_combobox.setItemText(23, _translate("MainWindow", "24"))
        self.days_combobox.setItemText(24, _translate("MainWindow", "25"))
        self.days_combobox.setItemText(25, _translate("MainWindow", "26"))
        self.days_combobox.setItemText(26, _translate("MainWindow", "27"))
        self.days_combobox.setItemText(27, _translate("MainWindow", "28"))
        self.days_combobox.setItemText(28, _translate("MainWindow", "29"))
        self.days_combobox.setItemText(29, _translate("MainWindow", "30"))
        self.add_operation_btn.setText(_translate("MainWindow", "Add"))
        self.main_tabWidget.setTabText(self.main_tabWidget.indexOf(self.today_tabWidget), _translate("MainWindow", "Today"))
        self.label.setText(_translate("MainWindow", "Book Title"))
        self.label_2.setText(_translate("MainWindow", "Book Id"))
        self.label_3.setText(_translate("MainWindow", "Book Auther"))
        self.label_5.setText(_translate("MainWindow", "Book Price"))
        self.label_6.setText(_translate("MainWindow", "Book Category"))
        self.upload_btn.setText(_translate("MainWindow", "upload book image"))
        self.upload_image_label.setText(_translate("MainWindow", "Not upload"))
        self.label_4.setText(_translate("MainWindow", "Book Publisher"))
        self.label_8.setText(_translate("MainWindow", "Description"))
        self.save_btn.setText(_translate("MainWindow", "Save"))
        self.search_btn.setText(_translate("MainWindow", "Search"))
        self.update_btn.setText(_translate("MainWindow", "Update"))
        self.delete_btn.setText(_translate("MainWindow", "Delete"))
        self.clear_btn.setText(_translate("MainWindow", "Clear"))
        self.books_tabWidget.setTabText(self.books_tabWidget.indexOf(self.Edit_book_tabWidget), _translate("MainWindow", "Edit Book"))
        item = self.show_books_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Book Id"))
        item = self.show_books_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Book Title"))
        item = self.show_books_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Book Auther"))
        item = self.show_books_tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Book Publisher"))
        item = self.show_books_tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Book Category"))
        item = self.show_books_tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Book Price"))
        self.books_tabWidget.setTabText(self.books_tabWidget.indexOf(self.show_books_tabWidget), _translate("MainWindow", "Show books"))
        self.main_tabWidget.setTabText(self.main_tabWidget.indexOf(self.QWidget), _translate("MainWindow", "Books"))
        self.label_7.setText(_translate("MainWindow", "Username"))
        self.label_9.setText(_translate("MainWindow", "Name"))
        self.label_10.setText(_translate("MainWindow", "Email"))
        self.label_11.setText(_translate("MainWindow", "Password"))
        self.label_12.setText(_translate("MainWindow", "Conferm Password"))
        self.user_radioButton.setText(_translate("MainWindow", "User"))
        self.admin_radioButton.setText(_translate("MainWindow", "Admin"))
        self.save_btn_2.setText(_translate("MainWindow", "Save"))
        self.search_btn_2.setText(_translate("MainWindow", "Search"))
        self.update_btn_2.setText(_translate("MainWindow", "Update"))
        self.delete_btn_2.setText(_translate("MainWindow", "Delete"))
        item = self.users_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Username"))
        item = self.users_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name"))
        item = self.users_tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Email"))
        self.main_tabWidget.setTabText(self.main_tabWidget.indexOf(self.users_tabWidget), _translate("MainWindow", "Users"))
        self.main_tabWidget.setTabText(self.main_tabWidget.indexOf(self.settings_tabWidget), _translate("MainWindow", "Settings"))
