# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_ui/login_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(1000, 600)
        login.setMaximumSize(QtCore.QSize(1000, 600))
        login.setStyleSheet("#login_tab {\n"
"font-size:20px;\n"
"}\n"
"#sign_up_tab {\n"
"font-size:20px;\n"
"}")
        self.tabWidget = QtWidgets.QTabWidget(login)
        self.tabWidget.setGeometry(QtCore.QRect(0, 70, 1261, 651))
        self.tabWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(140, 70, 731, 481))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.splitter_12 = QtWidgets.QSplitter(self.frame)
        self.splitter_12.setGeometry(QtCore.QRect(80, 80, 602, 240))
        self.splitter_12.setOrientation(QtCore.Qt.Vertical)
        self.splitter_12.setObjectName("splitter_12")
        self.splitter_5 = QtWidgets.QSplitter(self.splitter_12)
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName("splitter_5")
        self.label_11 = QtWidgets.QLabel(self.splitter_5)
        self.label_11.setStyleSheet("color: #7D7D7D;\n"
"font-family: \"Rounded Mplus 1c\";\n"
"font-size: 40px;\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"")
        self.label_11.setObjectName("label_11")
        self.splitter_6 = QtWidgets.QSplitter(self.splitter_12)
        self.splitter_6.setOrientation(QtCore.Qt.Vertical)
        self.splitter_6.setObjectName("splitter_6")
        self.splitter_8 = QtWidgets.QSplitter(self.splitter_6)
        self.splitter_8.setOrientation(QtCore.Qt.Vertical)
        self.splitter_8.setObjectName("splitter_8")
        self.label_14 = QtWidgets.QLabel(self.splitter_8)
        self.label_14.setStyleSheet("color: #7D7D7D;\n"
"font-family: \"Rounded Mplus 1c\";\n"
"font-size: 18px;\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"line-height: normal;")
        self.label_14.setObjectName("label_14")
        self.login_user_name = QtWidgets.QLineEdit(self.splitter_8)
        self.login_user_name.setMaximumSize(QtCore.QSize(16777215, 60))
        self.login_user_name.setStyleSheet("width: 590px;\n"
"height: 47px;\n"
"flex-shrink: 0;\n"
"border-radius: 13px;\n"
"border: 1.2px solid #DDD;\n"
"background: #FFF;\n"
"color: #7D7D7D;\n"
"font-family: \"Rounded Mplus 1c\";\n"
"font-size: 18px;\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"line-height: normal;\n"
"padding:5px;")
        self.login_user_name.setObjectName("login_user_name")
        self.splitter_11 = QtWidgets.QSplitter(self.splitter_6)
        self.splitter_11.setOrientation(QtCore.Qt.Vertical)
        self.splitter_11.setObjectName("splitter_11")
        self.label_15 = QtWidgets.QLabel(self.splitter_11)
        self.label_15.setStyleSheet("color: #7D7D7D;\n"
"font-family: \"Rounded Mplus 1c\";\n"
"font-size: 18px;\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"line-height: normal;")
        self.label_15.setObjectName("label_15")
        self.login_password = QtWidgets.QLineEdit(self.splitter_11)
        self.login_password.setMaximumSize(QtCore.QSize(16777215, 60))
        self.login_password.setStyleSheet("width: 590px;\n"
"height: 47px;\n"
"flex-shrink: 0;\n"
"border-radius: 13px;\n"
"border: 1.2px solid #DDD;\n"
"background: #FFF;\n"
"color: #7D7D7D;\n"
"font-family: \"Rounded Mplus 1c\";\n"
"font-size: 18px;\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"line-height: normal;\n"
"padding:5px;")
        self.login_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.login_password.setObjectName("login_password")
        self.login_btn = QtWidgets.QPushButton(self.frame)
        self.login_btn.setGeometry(QtCore.QRect(260, 360, 210, 51))
        self.login_btn.setMinimumSize(QtCore.QSize(210, 47))
        self.login_btn.setMaximumSize(QtCore.QSize(230, 55))
        self.login_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.login_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.login_btn.setStyleSheet("#login_btn{\n"
"border: 2px solid #1678F3;\n"
"border-radius:24px;\n"
"background-color: #1678F3;\n"
"color:white;\n"
"font-size:20px;\n"
"}\n"
"\n"
"#login_btn:hover{\n"
"background-color:#023436;\n"
"}")
        self.login_btn.setObjectName("login_btn")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame_2 = QtWidgets.QFrame(self.tab_2)
        self.frame_2.setGeometry(QtCore.QRect(20, 10, 971, 621))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.splitter_3 = QtWidgets.QSplitter(self.frame_2)
        self.splitter_3.setGeometry(QtCore.QRect(150, 20, 651, 371))
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter_7 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_7.setOrientation(QtCore.Qt.Vertical)
        self.splitter_7.setObjectName("splitter_7")
        self.label_13 = QtWidgets.QLabel(self.splitter_7)
        self.label_13.setStyleSheet("color: #7D7D7D;\n"
"font-family: \"Rounded Mplus 1c\";\n"
"font-size: 40px;\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"")
        self.label_13.setObjectName("label_13")
        self.layoutWidget = QtWidgets.QWidget(self.splitter_3)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter_10 = QtWidgets.QSplitter(self.layoutWidget)
        self.splitter_10.setOrientation(QtCore.Qt.Vertical)
        self.splitter_10.setObjectName("splitter_10")
        self.label_17 = QtWidgets.QLabel(self.splitter_10)
        self.label_17.setStyleSheet("color: #7D7D7D;\n"
"font-family: \"Rounded Mplus 1c\";\n"
"font-size: 18px;\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"line-height: normal;")
        self.label_17.setObjectName("label_17")
        self.sign_up_user_name = QtWidgets.QLineEdit(self.splitter_10)
        self.sign_up_user_name.setMaximumSize(QtCore.QSize(16777215, 60))
        self.sign_up_user_name.setStyleSheet("width: 590px;\n"
"height: 47px;\n"
"flex-shrink: 0;\n"
"border-radius: 13px;\n"
"border: 1.2px solid #DDD;\n"
"background: #FFF;\n"
"color: #7D7D7D;\n"
"font-family: \"Rounded Mplus 1c\";\n"
"font-size: 18px;\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"line-height: normal;\n"
"padding:5px;")
        self.sign_up_user_name.setObjectName("sign_up_user_name")
        self.verticalLayout.addWidget(self.splitter_10)
        self.splitter_13 = QtWidgets.QSplitter(self.layoutWidget)
        self.splitter_13.setOrientation(QtCore.Qt.Vertical)
        self.splitter_13.setObjectName("splitter_13")
        self.label_18 = QtWidgets.QLabel(self.splitter_13)
        self.label_18.setStyleSheet("color: #7D7D7D;\n"
"font-family: \"Rounded Mplus 1c\";\n"
"font-size: 18px;\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"line-height: normal;")
        self.label_18.setObjectName("label_18")
        self.sign_up_name = QtWidgets.QLineEdit(self.splitter_13)
        self.sign_up_name.setMaximumSize(QtCore.QSize(16777215, 60))
        self.sign_up_name.setStyleSheet("width: 590px;\n"
"height: 47px;\n"
"flex-shrink: 0;\n"
"border-radius: 13px;\n"
"border: 1.2px solid #DDD;\n"
"background: #FFF;\n"
"color: #7D7D7D;\n"
"font-family: \"Rounded Mplus 1c\";\n"
"font-size: 18px;\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"line-height: normal;\n"
"padding:5px;")
        self.sign_up_name.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.sign_up_name.setObjectName("sign_up_name")
        self.verticalLayout.addWidget(self.splitter_13)
        self.splitter_14 = QtWidgets.QSplitter(self.layoutWidget)
        self.splitter_14.setOrientation(QtCore.Qt.Vertical)
        self.splitter_14.setObjectName("splitter_14")
        self.label_19 = QtWidgets.QLabel(self.splitter_14)
        self.label_19.setStyleSheet("color: #7D7D7D;\n"
"font-family: \"Rounded Mplus 1c\";\n"
"font-size: 18px;\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"line-height: normal;")
        self.label_19.setObjectName("label_19")
        self.sign_up_address = QtWidgets.QLineEdit(self.splitter_14)
        self.sign_up_address.setMaximumSize(QtCore.QSize(16777215, 60))
        self.sign_up_address.setStyleSheet("width: 590px;\n"
"height: 47px;\n"
"flex-shrink: 0;\n"
"border-radius: 13px;\n"
"border: 1.2px solid #DDD;\n"
"background: #FFF;\n"
"color: #7D7D7D;\n"
"font-family: \"Rounded Mplus 1c\";\n"
"font-size: 18px;\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"line-height: normal;\n"
"padding:5px;")
        self.sign_up_address.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.sign_up_address.setObjectName("sign_up_address")
        self.splitter = QtWidgets.QSplitter(self.splitter_14)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.verticalLayout.addWidget(self.splitter_14)
        self.splitter_17 = QtWidgets.QSplitter(self.layoutWidget)
        self.splitter_17.setOrientation(QtCore.Qt.Vertical)
        self.splitter_17.setObjectName("splitter_17")
        self.label_20 = QtWidgets.QLabel(self.splitter_17)
        self.label_20.setStyleSheet("color: #7D7D7D;\n"
"font-family: \"Rounded Mplus 1c\";\n"
"font-size: 18px;\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"line-height: normal;")
        self.label_20.setObjectName("label_20")
        self.sign_up_password = QtWidgets.QLineEdit(self.splitter_17)
        self.sign_up_password.setMaximumSize(QtCore.QSize(16777215, 60))
        self.sign_up_password.setStyleSheet("width: 590px;\n"
"height: 47px;\n"
"flex-shrink: 0;\n"
"border-radius: 13px;\n"
"border: 1.2px solid #DDD;\n"
"background: #FFF;\n"
"color: #7D7D7D;\n"
"font-family: \"Rounded Mplus 1c\";\n"
"font-size: 18px;\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"line-height: normal;\n"
"padding:5px;")
        self.sign_up_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.sign_up_password.setObjectName("sign_up_password")
        self.verticalLayout.addWidget(self.splitter_17)
        self.sign_up_btn = QtWidgets.QPushButton(self.frame_2)
        self.sign_up_btn.setGeometry(QtCore.QRect(350, 420, 210, 51))
        self.sign_up_btn.setMinimumSize(QtCore.QSize(210, 47))
        self.sign_up_btn.setMaximumSize(QtCore.QSize(230, 55))
        self.sign_up_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sign_up_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.sign_up_btn.setStyleSheet("#sign_up_btn{\n"
"border: 2px solid #1678F3;\n"
"border-radius:24px;\n"
"background-color: #1678F3;\n"
"color:white;\n"
"font-size:20px;\n"
"}\n"
"\n"
"#sign_up_btn:hover{\n"
"background-color:#023436;\n"
"}")
        self.sign_up_btn.setObjectName("sign_up_btn")
        self.tabWidget.addTab(self.tab_2, "")
        self.layoutWidget1 = QtWidgets.QWidget(login)
        self.layoutWidget1.setGeometry(QtCore.QRect(90, 40, 761, 42))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.login_tab = QtWidgets.QPushButton(self.layoutWidget1)
        self.login_tab.setMinimumSize(QtCore.QSize(0, 40))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("qt_ui\\../assets/login.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.login_tab.setIcon(icon)
        self.login_tab.setIconSize(QtCore.QSize(24, 24))
        self.login_tab.setObjectName("login_tab")
        self.horizontalLayout.addWidget(self.login_tab)
        self.sign_up_tab = QtWidgets.QPushButton(self.layoutWidget1)
        self.sign_up_tab.setMinimumSize(QtCore.QSize(0, 40))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("qt_ui\\../assets/account.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sign_up_tab.setIcon(icon1)
        self.sign_up_tab.setIconSize(QtCore.QSize(24, 24))
        self.sign_up_tab.setObjectName("sign_up_tab")
        self.horizontalLayout.addWidget(self.sign_up_tab)

        self.retranslateUi(login)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "Form"))
        self.label_11.setText(_translate("login", "Get’s Started"))
        self.label_14.setText(_translate("login", "Username"))
        self.login_user_name.setPlaceholderText(_translate("login", "Insert Username"))
        self.label_15.setText(_translate("login", "Password"))
        self.login_password.setPlaceholderText(_translate("login", "Insert Password"))
        self.login_btn.setText(_translate("login", "Login"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("login", "Login"))
        self.label_13.setText(_translate("login", "Get’s Started"))
        self.label_17.setText(_translate("login", "Username"))
        self.sign_up_user_name.setPlaceholderText(_translate("login", "Insert Username"))
        self.label_18.setText(_translate("login", "Name"))
        self.sign_up_name.setPlaceholderText(_translate("login", "Name"))
        self.label_19.setText(_translate("login", "Email"))
        self.sign_up_address.setPlaceholderText(_translate("login", "Address"))
        self.label_20.setText(_translate("login", "Password"))
        self.sign_up_password.setPlaceholderText(_translate("login", "Password"))
        self.sign_up_btn.setText(_translate("login", "sign Up"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("login", "Sign Up"))
        self.login_tab.setText(_translate("login", "Login"))
        self.sign_up_tab.setText(_translate("login", "Sign Up"))
